set -g mouse on
set -g allow-passthrough on
set -g mode-keys vi
set -g history-limit 10000

set -g default-terminal screen-256color

set -s copy-command pbcopy

bind r source-file ~/.tmux.conf
set -g base-index 1

#resize panes with ctrl + hjkl
bind -n ^k resize-pane -U 5
bind -n ^j resize-pane -D 5
bind -n ^h resize-pane -L 5
bind -n ^l resize-pane -R 5

#jump panes with hjkl
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set-hook -g session-created "run-shell 'case \"#{session_name}\" in [0-9]*|default) tmux rename-session $(hostname -s) ;; esac'"

set-option -g set-titles on
set-option -g set-titles-string "#S / #W"
