#!/usr/bin/env bash
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Move dotfiles out of ~/
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export BUNDLE_USER_HOME="$XDG_DATA_HOME/bundler"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundler"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundler"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export DOTNET_CLI_HOME="$XDG_DATA_HOME"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export MPLCONFIGDIR="$XDG_CONFIG_HOME/matplotlib"
export NUGET_PACKAGES="$XDG_CACHE_HOME/nuget/packages"
export AZURE_CONFIG_DIR="$XDG_CONFIG_HOME/azure"
export HISTFILE="$XDG_STATE_HOME/bash/history"
export SHELL_SESSIONS_DISABLE=1

# Go
export PATH="$HOME/go/bin:$PATH"

if [ -S "$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh" ] && pgrep -qf com.maxgoedjen.Secretive.SecretAgent; then
  export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
fi
