#!/usr/bin/env bash

export APPLE=󰘳
export PREFERENCES=􀺽
export ACTIVITY=􀒓
export LOCK=􀒳
export WIFI_CONNECTED=􀙇
export WIFI_DISCONNECTED=􀙈
export ETHERNET_CONNECTED=󰈀

export AEROWORKSPACE_1=󰎦
export AEROWORKSPACE_2=󰎩
export AEROWORKSPACE_3=󰎬
export AEROWORKSPACE_4=󰎮
export AEROWORKSPACE_5=󰎰
export AEROWORKSPACE_6=󰎵
export AEROWORKSPACE_7=󰎸
export AEROWORKSPACE_8=󰎻
export AEROWORKSPACE_9=󰎾
