#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"
COLORS="$CONFIG_DIR/colors.sh"
ICONS="$CONFIG_DIR/icons.sh"

# shellcheck source=$COLORS
source "$COLORS"
# shellcheck source=$ICONS
source "$ICONS"

##### Bar Appearance

bar=(
  position=top
  height=40
  blur_radius=30
  color="$TRANSPARENT_BLACK"
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults

default=(
  padding_left=5
  padding_right=5
  icon.font="CaskaydiaCove Nerd Font:Bold:17.0"
  label.font="CaskaydiaCove Nerd Font:Bold:17.0"
  icon.color="$WHITE"
  label.color="$WHITE"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  popup.background.border_width=1
  popup.background.corner_radius=8
  popup.background.border_color=0x44ffffff
  popup.background.color=0xee1a1a2e
  popup.background.shadow.drawing=on
)

sketchybar --default "${default[@]}"

# -- Left side items --

source "$ITEMS_DIR/apple.sh"
source "$ITEMS_DIR/aerospace.sh"
source "$ITEMS_DIR/chevron.sh"

# -- Right side items --

source "$ITEMS_DIR/mic.sh"
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/input_source.sh"

sketchybar --hotload off

##### Force all scripts to run the first time (never do this in a script)

sketchybar --update
