#!/bin/bash

CONFIG_DIR="$HOME/.config/sketchybar"
PLUGINS_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

sketchybar --bar \
  height=37 \
  blur_radius=30 \
  position=top \
  sticky=off \
  color=$BAR_COLOR

sketchybar --default \
  icon.font="SF Pro:Regular:15.0" \
  icon.color=$WHITE \
  label.font="CaskaydiaCove Nerd Font:Regular:15.0" \
  label.color=$WHITE \
  background.color=$ITEM_BG_COLOR \
  background.height=24 \
  background.corner_radius=5 \
  icon.padding_left=5 \
  icon.padding_right=3 \
  label.padding_left=3 \
  label.padding_right=10 \
  background.padding_left=5 \
  background.padding_right=5

# -- Right side items --
source $ITEMS_DIR/calendar.sh
source $ITEMS_DIR/volume.sh
source $ITEMS_DIR/battery.sh
source $ITEMS_DIR/cpu.sh

# -- Left side items --
source $ITEMS_DIR/aerospace.sh
source $ITEMS_DIR/front_app.sh

sketchybar --update
